# Generated by Django 3.2.16 on 2022-11-07 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0004_auto_20221107_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(max_length=20, unique=True, verbose_name='学生姓名'),
        ),
    ]
